### ISSUE TITLE
Shopping cart inaccessable

### ISSUE THREAD

**Issue by Felix006** [j26design/Ecwid-Premium#11]
All customizing works (although images in products can disappear while in Muse). Upload shows images and all customization correctly.

Main problem - I can add items to the cart but whether using the shopping bag from ecwid or the cart counter from J26, **I can't access the cart itself to checkout.**

I have double checked the store URL and it is as the tutorial video example.
I can click the cart but there's no response.

Thank for any help you can give. The site is a temporary businesscatalyst site so I'll need to do an ftp upload to the real address once it's bug free.

Felix Danger

**Comment by jp26jp** [comment]
I'll take a look at everything today!

**Comment by Felix006** [comment]
Thank you.
The clients hoping to go live this week. I'm sure it's probably something
obvious.

Appreciate the help.
Felix

**Comment by jp26jp** [comment]
I'm sorry I'm getting to it a little later than expected but I found the problem and I'll have the update sent out today!

**Comment by Felix006** [comment]
Thank you. So it will be a widget update you'll send me? I really
appreciate the help and overall quick response.

Felix

**Comment by jp26jp** [comment]
If you're a lifetime member then it is synced to your cloud folder. If not, then the update was just sent out via email! Check your spam folder if it's not in your inbox. Let me know if you didn't get it or if this doesn't fix the issue.

I really like your store design by the way. Very nice job!

**Comment by Felix006** [comment]
Hi John.
I don't see it in my inbox or my junk folder and I only signed up to github
in order to place the ticket so I don't think I'm a lifetime member.

Could you please send me an email directly
felixisdanger@gmail.com

or shoot me a link to a download app like gdrive or dropbox?

Thanks
Felix

**Comment by Felix006** [comment]
John I found the update email.
Downloaded and imported the updates.
Still not working.

Do I need to use new widgets that were uploaded?
Or should the update automatically work on the code I have in there?
What changes do I need to make with these updates? There were two
storefront updates and one cart update but nothing for Add to Cart if
that's part of the problem.

Felix

**Comment by jp26jp** [comment]
You need to replace the existing cart with the new widgets. The _Add to Cart_ widget doesn't affect the store URL in the way that you were using them so those widgets weren't updated. Are you testing your website on a live version of your site?

**Comment by Felix006** [comment]
I'm using businesscatalyst.com in order to upload and test live. I'm still
getting the error code "cannot fine product.html"

Felix

**Comment by Felix006** [comment]
switched it back to just product.html as the store url and it blinks when I
click it but still nothing shows up.

**Comment by jp26jp** [comment]
Can you upload your Muse file (not the exported content) [here](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN)

**Comment by Felix006** [comment]
Whatever problem is happening is happening from the Add To Cart widgets.
I've placed a MuseThemes Widget into the page and it adopts the
customization from your widget but the shopping bag is disabled.
I remove your Add To Cart widgets and the shopping bag works.
I remove the store url from your widgets and the shopping bag redirects to
http://192.168.1.132:33334/#!/~/cart
Access Denied

**Comment by jp26jp** [comment]
Can you upload your Muse file

**Comment by Felix006** [comment]
I went with customizing Ecwid CSS in their store and applied it to a
MuseThemes widget. I'd still like to be able to use this since I bought it
but I'll have to try it on another site since the client was rushing me to
fix it.

As to the problem itself, the AddToCart widget by itself made the error.
Even when used with another vendors cart/bag, the AddToCart disabled it.
Everything worked as soon as I removed the AddToCart widget.

I have another that I'm going to be building this week that needs it.
Although that has it's own concerns due to recurring billing but if I wind
up using your widget again, I'd like to be able to contact you.

Thanks again, John

**Comment by Felix006** [comment]
The current (fixed) version doesn't have your widgets in it. The previous
upload that I sent you has the AddToCart widgets in it.

**Comment by jp26jp** [comment]
I'll be able to get an idea of what is going on if you upload your Muse file.

**Comment by Felix006** [comment]
see attached

Felix

**Comment by jp26jp** [comment]
I'm not seeing anything attached. Would you mind uploading it here: https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN

**Comment by Felix006** [comment]
Done.
Thanks again, John

Felix

**Comment by jp26jp** [comment]
I need the Muse file, not the exported HTML.

**Comment by Felix006** [comment]
Ok that's been uploaded same place now
