### ISSUE TITLE
Padding issue on iPhone for Checkout with Stripe

### ISSUE THREAD

**Issue by orgongansol** [j26design/Ecwid-Premium#12]
![artboard 2](https://cloud.githubusercontent.com/assets/19664141/16123247/9495d5c2-33ea-11e6-80f5-c6f382041586.png)

When used on iPhone, the Ecwid Widget has a padding on the right side because the total amounts are displayed on a line instead of being stacked.

**Comment by jp26jp** [comment]
This issue will be fixed in Storefront V8.17.3!
