### ISSUE TITLE
Disappearing Counter

### ISSUE THREAD

**Issue by sk8phil** [j26design/Ecwid-Premium#13]
I just installed the latest version (V8.17.3), and almost everything looks good. There is still one issue that is prevalent. The counter appears on every page except for the “Shop page”. Can you please advise as to what is going on here?  Thanks.

**Comment by jp26jp** [comment]
It's fixed in Shopping Cart (Cart Counter) V1.3.2 and the update was just sent out!

**Comment by sk8phil** [comment]
I'll check it out. Thanks. 

Phillip Romero

Sent from my iPhone

On Jun 23, 2016, at 2:40 AM, John R Perry <notifications@github.com> wrote:

It's fixed in Shopping Cart (Cart Counter) V1.3.2 and the update was just sent out!

**Comment by sk8phil** [comment]
Awesome.  I just tried it and it appears to be functioning correctly.
Thanks for your help.

On Thu, Jun 23, 2016 at 2:40 AM, John R Perry <notifications@github.com>
wrote:

> It's fixed in Shopping Cart (Cart Counter) V1.3.2 and the update was just
> sent out!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/j26design/Ecwid-Premium/issues/13#issuecomment-228000026>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS0198K695O28eeZC3jHvTEq1QCC-_Y-ks5qOlSmgaJpZM4I8dP4>
> .
>



-- 
-Phillip Romero

**Comment by jp26jp** [comment]
Great news!
