### ISSUE TITLE
 Ecwid e-commerce widget

### ISSUE THREAD

**Issue by ingbingbong** [j26design/Ecwid-Premium#14]
Problem 1:

i've added a category, product to the store, and applied within ecwid some options to the product. these options are adding greeting cards to the selcted product, and option 2 adding a personal message to it. All of which appear and seem to work fine. however once i applied options to the product, i can’t add the product to the cart anymore. i previewed the store within ecwid, and in there it works well… when i apply the widget, some connection seems to be lost or missing. can you help please?

Problem 2:
We’ve got a flouncy script typeface for the title, (i purchased the web-licence through myfonts) which will not activate or chow up in the shop…
and a sans serif for bodycopy, which seems to be working, but not quite as i specified..

could you help with that please.

i tried to upload the file, but it said it was too big. 23.5 MB. don't know how to make it smaller.

http://decadencedelivered.businesscatalyst.com/cookies-shop.html

**Comment by jp26jp** [comment]
First, please update to the latest widgets so that I can see if it's still an issue.

**Problem 1:**
I'm not able to reproduce this issue. Is it still happening?

**Problem 2:**
Fonts that are not from WebFont or TypeKit can be complicated. 

Set the font type to `__Al Fresco_5` like this:
<img src="http://i.imgur.com/RJc5N3W.png" width="300px"/>

Set the font-family to `cursive`.

**Comment by ingbingbong** [comment]
Hi J.

thank you so much for looking into this…
i was just about to contact you today, to thank you for fixing the shop issue.

It just suddenly started to work yesterday!

I think i’ve updated my version of Ecwid 
(all you do is click on the widget and muse does it automatically, right? - sorry i’m still learning, especially as it’s all self-taught)

but in my dropdown, all i have to choose from is serif, sans serif and monospace see screen-grab attached.

again, many thanks for the help

Inge




Inge Weitzel
________________

T: 	01 663 762 310
M:	079 49 09 00 89

**Comment by jp26jp** [comment]
Whoops, that's right. Set it to `sans-serif`. The _font-family_ is just a fallback so it isn't necessary, it's just there in case.

The updates will be added to Muse but you actually have to replace the new ones with the old ones.

**Comment by ingbingbong** [comment]
Wonderful, thank you very much!

**Comment by ingbingbong** [comment]
Hi J,

i’m sorry to disturb you again…
i managed to get the typeface to work, thank you very much,

but i now have two other issues, that i’ve been trying to solve on the same website… 
i’ve gone through the widget options 1 by 1, and i just can’t find how to alter,

1. : 
 i want to style or even better, get rid of the "sort by" drop down, there are only 6 products in the store...



2. : 
i wanted to style the Price (i found where i can change the colour, but i’m still lost to where i can adjust the size), 




Please help

Inge

**Comment by jp26jp** [comment]
1. This isn't available yet, but I've added it as a [feature request here](https://github.com/j26design/Ecwid-Premium/issues/17)

2. In the Storefront, there is a _Size_ section. At the bottom of that section are 2 options: _Price (Product Details)_ and _Price (Product Grid)_. Those will allow you to change the size of the price text.

**Comment by jp26jp** [comment]
Whoops, I forgot that the remove 'Sort by' dropdown feature is actually available. It's in the _Product Grid_ widget.

**Comment by ingbingbong** [comment]
Good morning!!

wow i really hope there is a whole team of you working on these… or you are working far tooo hard - 3 am?! 

1. : 

YAY found that one!!

2.:
i can’t find the options you discribed, all the options i’ve got to choose from in the size section are in the screen-grab below

am i looking in the wrong place? have i got the latest version of your widget?

many thank 
Inge

**Comment by jp26jp** [comment]
Probably not, the latest version is V8.17.4.

I send updates via email so check your spam folder. If it isn't there, let me know and I'll see if your email has been added to the list.

**Comment by ingbingbong** [comment]
I’m well behind!!!
V8.12!

i’ve checked my spam folder, but it get deleted every few days…
could you forward me the latest version 
pls?

many thanks
Inge



Inge Weitzel
________________

T: 	01 663 762 310
M:	079 49 09 00 89

**Comment by jp26jp** [comment]
I just resent the latest email. You were already on the list so it's probably been going to your spam folder.

**Comment by ingbingbong** [comment]
Good morning, 

thanks to your support, i’m slowly but surely getting there..

i was just about to re-do everything with the new widgets you shared yesterday, and unfortunately 
the "get style sheet text" link has gone a missing or lost see text copied in below.

the same error goes as well for the mail chimp signup widget.
do you still need it?

kind regards
inge


Not Found

The requested URL /j-26-font-icon-stylesheet-text.html was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Apache Server at ecommerce.j-26.com Port 80
