### ISSUE TITLE
Submenus don't match size of Menu

### ISSUE THREAD

**Issue by SourDiesel** [j26design/Ecwid-Premium#15]
The horizontal navigation submenu boxes are shortened (in size) in all instances with exception of the last horizontal menu box . This is the only place it displays correctly. In all other instances, the box only fits the text in the box.

http://www.positivesleepsolutions.com/shopping.html

![j26-menu-issues](https://cloud.githubusercontent.com/assets/20111755/16307075/92423582-3925-11e6-94f8-340121cbe024.jpg)

**Comment by SourDiesel** [comment]
![j-26](https://cloud.githubusercontent.com/assets/20111755/16429266/7e0de90c-3d3b-11e6-8314-2a9223c944a4.jpg)

**Comment by jp26jp** [comment]
I'm aware of this issue. I will get to it as soon as I can.

**Comment by SourDiesel** [comment]
Better that a month has passed - I paid for a product that doesn't work. What gives?

**Comment by jp26jp** [comment]
The whole store doesn't work or just the menu?

**Comment by SourDiesel** [comment]
The menu

**Comment by SourDiesel** [comment]
John - just the menu doesn't work properly.

**Comment by jp26jp** [comment]
It's almost finished. I should have an update sent out in 48 hours

**Comment by SourDiesel** [comment]
Thanks for the update John.

**Comment by jp26jp** [comment]
The update for the widget was just sent out!
