### ISSUE TITLE
Blurred on second product image

### ISSUE THREAD

**Issue by chuckmyers** [j26design/Ecwid-Premium#18]
Grid images are fine, but when clicked, the image becomes blurred in Adobe muse. It looks ok in Ecwid. What could the problem be?

**Comment by jp26jp** [comment]
What's the url?

**Comment by chuckmyers** [comment]
Dirtballfactory.com

Go to store

From:  John R Perry <notifications@github.com>
Reply-To:  j26design/Ecwid-Premium
<reply+01345005deaea1f0107dad13d17959b1e93482ecf371891392cf00000001138b800e9
2a169ce09b5be68@reply.github.com>
Date:  Wednesday, June 29, 2016 at 8:24 AM
To:  j26design/Ecwid-Premium <Ecwid-Premium@noreply.github.com>
Cc:  Charles Myers <chuck@dirtballfactory.com>, Author
<author@noreply.github.com>
Subject:  Re: [j26design/Ecwid-Premium] Blurred on second product image
(#18)


What's the url?


You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/j26design/Ecwid-Premium/issues/18#issuecomment-229340409
> , or mute the thread
<https://github.com/notifications/unsubscribe/ATRQBYrOh5IVoTTGDP8abD_Ip5sPDR
pdks5qQmQOgaJpZM4JBDDp> .

**Comment by jp26jp** [comment]
It looks like you uploaded an image that's only 234x250. Once you upload a larger image it will not be blurry.
