### ISSUE TITLE
Whitespace below storefront

### ISSUE THREAD

**Issue by Moonlight63** [j26design/Ecwid-Premium#25]
There seems to be white space below the storefront on the initial page load, and it disappears if you simply resize the page. Not sure if this is only on responsive sites or not. Not a huge deal if there isn't anything below the storefront, but it's still unintended behavior.

![1](https://cloud.githubusercontent.com/assets/7518189/17088590/1bceead8-51d2-11e6-8711-aec73f194b3e.PNG)
![2](https://cloud.githubusercontent.com/assets/7518189/17088591/1bd136c6-51d2-11e6-91e4-0fd476402ea6.PNG)

.

**Comment by j-vic** [comment]
I'm getting this same issue as well. Also, I see from your screenshots that you're also getting the double vertical scrollbars.

**Comment by Moonlight63** [comment]
Oh, yea that to!

**Comment by jp26jp** [comment]
Are the double vertical scrollbars happening outside of Muse?

**Comment by Moonlight63** [comment]
I don't think so, but I've only tried chrome.

**Comment by j-vic** [comment]
Yeah they are. My website was uploaded via ftp and they're showing.

**Comment by j-vic** [comment]
Yeah they are. My website was uploaded via ftp and they're showing.

**Comment by jp26jp** [comment]
Okay, I've moved the [double vertical scrollbars issue over here](https://github.com/j26design/Ecwid-Premium/issues/26). I'll follow up on that issue in just a moment.

It's been difficult to pin down the exact cause of the white space, because, in my experience, it has been inconsistent. However, I haven't seen that large of a gap before so hopefully your Muse site will give me a little more insight. Would you mind [uploading it here](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN) so I can take a look?

**Comment by Moonlight63** [comment]
Yes I will, one moment.

**Comment by Moonlight63** [comment]
Just uploaded a watered down file. Strangely, the problem seems to have
amplified...

**Comment by jp26jp** [comment]
I've passed this onto one of the devs on the Muse Team so I will get back to you on this when I know more.

**Comment by Moonlight63** [comment]
Cool

**Comment by Moonlight63** [comment]
Hey, any news on this yet?

**Comment by jp26jp** [comment]
No, I've sent it to the Muse dev team so I'm hoping they'll figure out what's going on soon.

**Comment by Moonlight63** [comment]
ok, I've been make a few sites, and was still seeing the issue, so was just
checking in. Thanks!

**Comment by jp26jp** [comment]
I forgot to mention that the last update might have resolved the issue. Update the storefront to version 8.17.3. Let me know if it seems to fix the issue!

**Comment by Moonlight63** [comment]
Just upgraded everything, and I can confirm that 8.17.13 does NOT fix this issue. BUT, double scrollbars seem to be fixed.

**Comment by jp26jp** [comment]
This was resolved with the most recent update that was sent out today (01/03/2017). Feel free to reopen the issue if you are still experiencing a problem.
