### ISSUE TITLE
Double vertical scrollbars

### ISSUE THREAD

**Issue by jp26jp** [j26design/Ecwid-Premium#26]

**Comment by jp26jp** [comment]
@j-vic what's the URL of your store? Can you also [send me the Muse file](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN)?

**Comment by j-vic** [comment]
Sure,

The URL is http://geishaceramics.com.au

The file is too big to send.

**Comment by jp26jp** [comment]
Which browser and device are you getting the double scrollbars in

**Comment by j-vic** [comment]
I'm seeing on PC with Chrome. I haven't tried in other browsers yet.

**Comment by jp26jp** [comment]
Okay, I see the issue but I'm going to need to see the file to be able to identify the cause. If you [join this folder](https://www.dropbox.com/l/scl/TLyUysxAvcnmXzUlVFHgTn) and upload your muse file there, it will sync the file to my comp.

**Comment by j-vic** [comment]
Cool, actually, could you share the folder with my personal email? justin.mcvicar@live.com.au

**Comment by j-vic** [comment]
Uploading it now. My internet is crap atm, so it'll take about an hour apparently.

**Comment by j-vic** [comment]
4 minutes to go

**Comment by j-vic** [comment]
Ok, it's in there

**Comment by j-vic** [comment]
How did you go with it?

**Comment by j-vic** [comment]
@jp26jp How did you go with it dude?

**Comment by jp26jp** [comment]
Haven't had a chance to look yet.

**Comment by jp26jp** [comment]
The code that you put in the master page is causing this. 

Change this...

```
<style type="text/css">
html,body{overflow-x:hidden; margin:0; padding:0;}
</style>
```

to this:

```
<style type="text/css">
body{overflow-x:hidden; margin:0; padding:0;}
</style>
```

**Comment by j-vic** [comment]
Worked like a charm. Thanks so much!

**Comment by jp26jp** [comment]
Haha not a problem!
