### ISSUE TITLE
Change Font in ECWID

### ISSUE THREAD

**Issue by orenshim** [j26design/Ecwid-Premium#27]
Hi John,

My name is Oren from Israel, I would like to use the font of text - OPEN SANS HEBREW. I've set up in Adobe Muse font using the Text window and still there is no change in the browser. How can I change the font? Also, I will be happy if you will support RTL

http://xtreme-hobbyracing.businesscatalyst.com/חנות-מקוונת.html

Thanks!

![text panel](https://cloud.githubusercontent.com/assets/20366453/17191506/d604ccb0-5452-11e6-9066-83571940194e.jpg)
![store panel](https://cloud.githubusercontent.com/assets/20366453/17191509/d95d126e-5452-11e6-8cee-79f290119f20.jpg)

**Comment by jp26jp** [comment]
RTL support will be in the next update. To find the font name, [use this widget](https://www.j-26.com/tools/helpers/font-finder/).
