### ISSUE TITLE
Ecwid Premium - Storefront - Buttons - V1.8.1

### ISSUE THREAD

**Issue by aebasa** [j26design/Ecwid-Premium#29]
Hi,
The lowest I can make the min width of button is 130px, can you please lower the min amount, would love to style a button at min 80px width
Thanks :)

**Comment by jp26jp** [comment]
I can make that size available but the text will overflow at anything under 110px

**Comment by aebasa** [comment]
I see what you mean, would it be better for me to just add custom CSS for buttons that I want to be smaller in width? I want to use icons for my ADD TO BAG and CART COUNTER buttons and make my DETACHED CART button 90px width. See attached example.
Thanks :)
<img width="292" alt="screen shot 2016-08-01 at 2 56 14 pm" src="https://cloud.githubusercontent.com/assets/20750621/17284248/26e813b4-57f8-11e6-9747-fbd3136890d7.png">

**Comment by jp26jp** [comment]
The minimum width of the button was set to 0 in the last update that was just sent out!

**Comment by aebasa** [comment]
Thanks so much John!
Alicia :)
