### ISSUE TITLE
Type face is not displaying correctly on Ecwid.

### ISSUE THREAD

**Issue by ingbingbong** [j26design/Ecwid-Premium#30]
Hi J26,

i've had this problem before, with one of my other ecwid stores, but with a different typeface.

Store
http://www.squidgeandpip.com/shop.html

the typeface i like displaying is Museo Slab 100 / 700 and 300

it worked previously, with the old Ecwid Widget, but now that 
i've updated the clients shop, with the new Ecwid Widget, it just won't have it.

When i'm in Preview in muse it looks fine, when i launch it on my mac is fine... my clients Mac not, and neither on the iPad or iPhone.

can you help please?

**Comment by jp26jp** [comment]
First, make sure you're entering the correct font name [with this tool](https://www.j-26.com/tools/helpers/font-finder/). If that doesn't help, send your [Muse file here](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN).

**Comment by ingbingbong** [comment]
it worked perfectly, thank you very much for your prompt help!

**Comment by jp26jp** [comment]
Awesome!
