### ISSUE TITLE
"coupon code" Input field is playing up with the latest update.

### ISSUE THREAD

**Issue by ingbingbong** [j26design/Ecwid-Premium#31]
i've got ecwid looking into it as well, but they suggested, to have you give it a once over as well please....

it looks beautiful, just as i'd like it to, but the i try and input anything, the screen scrolls up and typing doesn't produce anything.. i thought maybe the text is set too big or too little or maybe even in white.... but i checked. and changed things, even made the field really big, nothing.

I just noticed, the same fault applies to the quantity box, you can't add to it... and with the product details, only half of the number shows.

the website is http://www.squidgeandpip.com/shop.html#shopentrance

RECENT DEVELOVMENT

i deleted the storefront, and placed it in again, and that seems to have fixed the input issue, but the problem with the quantity  showing in the product detail panel still remains.. not sure if this is something you can help with, as it only seems to show up as a problem on safari!

**Comment by jp26jp** [comment]
Oh wow I love this site!

I'll take a look

**Comment by ingbingbong** [comment]
Hi! 
Thank you very much! It s always great to Get lovely Feedback, Especially as I'm very new to web design and muse. 

I've been sent some clue to the problem from ecwid who've been looking into this as we'll... See below:

Does that mean, if I add the bit of code, which is on the master page, to the ecwid design bit as described below, that this will fix? 


I have checked the source code of your site at http://www.squidgeandpip.com/shop.html#!/Squidge-Sensory-Teething-Toy/p/62155190/category=18409649and see that there are CSS codes added inside <style></style> tags to the source HTML code of your site and this causes the problem with the quantity field.

We recommend to add CSS changes right in Ecwid in your active CSS theme in your Ecwid Control Panel > Settings > Design.

Please let me know if you need help with this.

Thank you!

Best regards,
Clara K.
Ecwid Customer Care team

**Comment by jp26jp** [comment]
Yes I see the issue and it's coming from the 4th spacing inside the global widget being too large. I will fix the widget and send out an update today!

**Comment by jp26jp** [comment]
This update was fixed in the update that was just sent out!

**Comment by ingbingbong** [comment]
Thank you very much, as always.

**Comment by jp26jp** [comment]
Let me know when you've updated the widgets, I'd love to see how it looks!

**Comment by ingbingbong** [comment]
Hi John,

thank you very much for the interest..

I tried to fix it all before i went on holiday, but wasn’t entirely successful.
the coupon code worked, and i updated it, but the Quantity input fix (where that extra space in front was causing the numbers not to display) was then interfeering with it all.

now that i’m back at my desc, i will look and re-do the lot with the very latest updates (i’m getting confused now which ones are which)
and let you know as soon as i have managed to do it.


again thank you so much for all your help!

Inge

**Comment by ingbingbong** [comment]
Hi John,

happy new year!
i wanted to say a big thank you for the latest update. 
It’s been a very long time ago since my original request, but i have not had chance to write back to you any earlier.

If you are still interested in the result of the shop, below is the link to the website.

http://www.squidgeandpip.com/shop.html <http://www.squidgeandpip.com/shop.html>

All the features work now perfectly, and my client is very happy with it also.
If you where to do any other updates, the only visual suggestion i would have, is to fix the akward up/down spaces between the 
Price/Qty/subtotal  column. see screengrab attached.

as always thank you
Inge
