### ISSUE TITLE
Bugs in ecwid

### ISSUE THREAD

**Issue by orenshim** [j26design/Ecwid-Premium#34]
Hi John,

I sent you two weeks ago an application for debugging Ecwid and have not received a response.
I resubmit a request, I would be happy if you can deal immediately with serious bugs listed in this e-mail attachments. The site should be released, and now these bugs really get in the way.

http://xtreme-hobbyracing.businesscatalyst.com/חנות.html#!/DJI-PHANTOM-3-ADVANS/p/69432020/category=20550320

Thanks
![chackout form bugs](https://cloud.githubusercontent.com/assets/20366453/18078663/73bb9b6c-6e95-11e6-9245-725720d665b1.jpg)
![login form bugs](https://cloud.githubusercontent.com/assets/20366453/18078662/73ba2854-6e95-11e6-91a7-668e713ef4ab.jpg)

**Comment by jp26jp** [comment]
Please switch to the newest version of the widget and let me know if anything isn't working.

**Comment by orenshim** [comment]
Hi John,

Do I have to drag the widget is updated into the widget instead of the
previous file and re-enter all settings? If so, this is a big problem
because it creates a new job for me and tedious

**Comment by jp26jp** [comment]
Okay, well then I'll just assume the problem is fixed until you have enough time to update the widget.
