### ISSUE TITLE
when using the standalone add to cart button the popup will not display correctley

### ISSUE THREAD

**Issue by jeraldmartin3** [j26design/Ecwid-Premium#35]
![capture](https://cloud.githubusercontent.com/assets/21366370/18136612/437500d6-6f5a-11e6-8647-b962225c2c62.JPG)

**Comment by jp26jp** [comment]
This was resolved with the most recent update that was sent out today (01/03/2017). Feel free to reopen the issue if you are still experiencing a problem.
