### ISSUE TITLE
Bug in Ecwid 

### ISSUE THREAD

**Issue by orenshim** [j26design/Ecwid-Premium#36]
Hi John,
Thank you for the reference and bug fixes.
New bug I encountered - when signaling the possibility Terms & Conditions, there is a sentence in Hebrew in reverse order: תנאי השימוש אני מסכים עם
Should be: **אני מסכים עם תנאי השימוש**

I would be grateful if you could deal with it quickly.

Thank you!

![terms conditions](https://cloud.githubusercontent.com/assets/20366453/18417173/56345c50-7831-11e6-99ef-1c2171b89796.jpg)

**Comment by jp26jp** [comment]
This will be fixed in the next update! As mentioned here: #38
