### ISSUE TITLE
ecwid premium navigation v2.0.1

### ISSUE THREAD

**Issue by Bchila** [j26design/Ecwid-Premium#39]
i have widget in master page. links work well on ALL of the child/slave pages, except for the blog page of site www.ganargear.com   wierd!

Blog is a native blog system by QooQee, using php scripting for server side coding & databasing (all made by qooqee)

when i hover over links i get the url show up at bottom of browser, and drop-downs extend out, but just wont link to the store, like dead links

thanks!
Brett

**Comment by jp26jp** [comment]
[Would you mind sending me the file](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN)?

**Comment by Bchila** [comment]
John, any updates on this support ticket??  thx!


Regards,
Brett Chila
Owner/Designer
Triune Design Studio
Jacksonville, Florida USA
Office: 1.904.300.3474

NEWSLETTER SIGNUP: http://eepurl.com/b3jGFL

www.TriuneDesignStudio.com          (website)
www.Behance.net/TriuneMultimedia    (online portfolio)
www.Facebook.com/TriuneDesignStudio (Facebook)
www.LinkedIn.com/in/BrettChila      (LinkedIn)
www.Google.com/+TriuneMultimedia    (Google+)

Graphic Design | Video/Motion Graphics | Websites & Hosting Solutions | Apparel & Printing

"Specializing in Graphic Design for the Apparel Industry"

"For God so loved the world, that He sent His one & only Son,
that whosoever would believe in Him, would not perish,
but have eternal life."  -John 3:16

**Comment by jp26jp** [comment]
Sorry, taking a look now. So the blog page is the one you're referring to?

**Comment by jp26jp** [comment]
I see the issue, I just have no way of knowing how or why it's happening because QooQee makes their code impossible to read. So this is going to have to be something that QooQee changes about their widget. There is a conflict with the ajax code which means that the issue is on QooQee's side because Ecwid is able to be integrated into many other ajax generated platforms.

**Comment by Bchila** [comment]
thx John, ill ask QooQee


ANNOUNCEMENT!!! WE NOW OFFER APPAREL & PRINTING SERVICES

Regards,
Brett Chila
Owner/Designer
Triune Design Studio
Jacksonville, Florida USA
Office: 1.904.300.3474

NEWSLETTER SIGNUP: http://eepurl.com/b3jGFL

www.TriuneDesignStudio.com          (website)
www.Behance.net/TriuneMultimedia    (online portfolio)
www.Facebook.com/TriuneDesignStudio (Facebook)
www.LinkedIn.com/in/BrettChila      (LinkedIn)
www.Google.com/+TriuneMultimedia    (Google+)

Graphic Design | Video/Motion Graphics | Websites & Hosting Solutions | Apparel & Printing

"Specializing in Graphic Design for the Apparel Industry"

"For God so loved the world, that He sent His one & only Son,
that whosoever would believe in Him, would not perish,
but have eternal life."  -John 3:16
