### ISSUE TITLE
"Remove 'Add more' Button" does not work

### ISSUE THREAD

**Issue by C3LLoX** [j26design/Ecwid-Premium#42]
Hey!
As the title says, in your Muse-Plugin, the "Remove 'Add more'-Button" does not work for me. 
If I uncheck the box with "Add Icon", obvious, just the Icon disappears.

Sorry for my bad english.

I thank you for this very helpful widget and hope you can fix this soon. 

Dominic

**Comment by jp26jp** [comment]
Oh weird. Let me take a look and get back to you!

**Comment by jp26jp** [comment]
I see the issue. I'll have an update out in 24 hours!

**Comment by jp26jp** [comment]
This bug was fixed in the most recent update!
