### ISSUE TITLE
Problems with NEXT/PREVIOUS arrows buttons in Firefox

### ISSUE THREAD

**Issue by fmsign** [j26design/Ecwid-Premium#43]
Hi!
I have a problem with the display of arrows in the item card. In Mozila Firefox they don't appear ((( How can I fix it?

![screen](https://cloud.githubusercontent.com/assets/23125106/19814498/11faa2f2-9d47-11e6-9b51-fc1152ae4628.jpg)

**Comment by fmsign** [comment]
XML error

**Comment by jp26jp** [comment]
This will hopefully be fixed in the next update!

**Comment by jp26jp** [comment]
This was resolved with the most recent update that was sent out today (01/03/2017). Feel free to reopen the issue if you are still experiencing a problem.
