### ISSUE TITLE
Bug? Font is not resizing correctly - ecwid navigation 2.0.1. widget

### ISSUE THREAD

**Issue by Squitsh** [j26design/Ecwid-Premium#44]
![canvas view](https://cloud.githubusercontent.com/assets/23510937/20369816/78305828-ac5b-11e6-8b9e-6c8a630bf421.JPG)
![browser-view](https://cloud.githubusercontent.com/assets/23510937/20369820/7dfd2b14-ac5b-11e6-9067-13723b2bd978.JPG)

Hi J26,

just bought your ecwid premium widgets a bit ago. I really love them and you did a great job. Thx for that. 

Unfortunatly I have a problem with the navigtation 2.0.1 widget. It is placed at the header of my master page A. The font-size which I define in the widget is shown in the live preview on the canvas correctly. But if I start the browser preview the size always shrinks to i guess 10 pt. Regardless which size it had in the canvas. 

This error occurs only if the navigation is shown on the same page as the main "all storefront widget". The menu font size is displayed corretly at other pages without the all storefront widget. But there it is not needed :-) 

Do you have any idea what the problem might be? Thx for you anser in advanve. 

Cheers 
Markus
![canvas view](https://cloud.githubusercontent.com/assets/23510937/20369816/78305828-ac5b-11e6-8b9e-6c8a630bf421.JPG)

**Comment by jp26jp** [comment]
Hmmm I'll look into this and get back to you! Thank you for reporting this issue.

**Comment by jp26jp** [comment]
This was resolved with the most recent update that was sent out today (01/03/2017). Feel free to reopen the issue if you are still experiencing a problem.
