### ISSUE TITLE
Latest Ecwid store update

### ISSUE THREAD

**Issue by 512studio** [j26design/Ecwid-Premium#46]
I've been getting a demo store even though I use the client's store ID in all the right places.
So confused? Maybe I missed something. Help.

http://www.perfectoil.com  LIVE PAGE
http://perfectoil01.businesscatalyst.com WITH UPDATED WIDGET.

**Comment by jp26jp** [comment]
This can happen if you're using another widget that requires the Ecwid store ID. So check any shopping carts, search bars, etc.
