### ISSUE TITLE
Related Products Name

### ISSUE THREAD

**Issue by Morphosx** [j26design/Ecwid-Premium#47]
Can you add a option in Product Details to change the name of the section "Related Products"?

Best Regards

Antonio De Leon
adl@morphos.com

<img width="456" alt="adobe muse ccref002" src="https://cloud.githubusercontent.com/assets/24576853/21204709/42e04510-c21e-11e6-8d5c-2b21475b6acc.png">

**Comment by jp26jp** [comment]
You can actually use the [label editor](https://muse.j-26.com/labelEdit) to do this
