### ISSUE TITLE
Add to cart button doesn't disappear when Add More button shows up. (and more)

### ISSUE THREAD

**Issue by Moonlight63** [j26design/Ecwid-Premium#48]
Pretty much exactly the title. When you put an item in your cart, the Add More button shows up, but the add to cart button stays there. Also, the "Remove Add More Button" under storefront buttons: plugins doesn't remove the button. Currently I am removing the button by applying a stylesheet, but this leaves the Add to cart button, when I really want it to change to say "Add More."

Also, this is a completely different topic, but when you first enter checkout, it seems as though the custom style sheet that the widget applies doesn't load properly. (Again, I have fixed this by loading a style sheet in ecwid control panel, but I shouldn't have to) 

Picture below: before and after:
![capture](https://cloud.githubusercontent.com/assets/7518189/21488387/f2517d1a-cb93-11e6-85dc-64edad241236.PNG)
![capture2](https://cloud.githubusercontent.com/assets/7518189/21488389/f5a49876-cb93-11e6-9bb3-173b1f83ce35.PNG)

Oh, and this check box is messing with my OCD:
![capture3](https://cloud.githubusercontent.com/assets/7518189/21488397/0681678c-cb94-11e6-9f67-af9b208cd8a5.PNG)

Ok, I think i'm done complaining...... Let me know if I can provide any more information.

Here is the CSS I have loaded in ecwid as a hotfix.

> html#ecwid_html body#ecwid_body div.ecwid-Checkout-ShippingAddress-container {
>     background-color: transparent;
> }
> 
> .ecwid-AddressForm-fields, .ecwid-Checkout-DeliveryMethod{
>     background-color: #F5F5F5!important;
>     padding: 30px!important;
>     margin-bottom: 30px!important;
>     display: block!important;
> }
> 
> .body-panel:not([aria-hidden="true"]), html#ecwid_html body#ecwid_body .ecwid-Checkout-ShippingAddress table.ecwid-Checkout-blockTitle td[align="left"]{
>     background-color: #F5F5F5!important;
>     padding: 30px!important;
>     margin-bottom: 30px!important;
>     display: block!important;
> }
> 
> html#ecwid_html body#ecwid_body .ecwid .ecwid-btn--addMore {
>     margin-right: 10px;
>     display: none;
> }
> html#ecwid_html body#ecwid_body .ecwid .ecwid-btn--secondary {
>     margin-top: 10px;
> }
> 
> .verticalspacer {
>     clear: none;
> }

btw the last part there fixes the large space at the bottom of the page glitch.

**Comment by jp26jp** [comment]
There was a bug in the Global widget that was messing with the mentioned issues above. The update will be sent out today that will also fix the [whitespace](https://github.com/j26design/Ecwid-Premium/issues/25) issue. Thank you very much for the detailed information.

**Comment by Moonlight63** [comment]
I love hearing this! Hey, not to add to your plate even more, but..... The
double scroll bar is back... DUN DUN DUN!!!

**Comment by Moonlight63** [comment]
I have now found that disabling overflow-x: hidden; on the <body
id="ecwid_body" ... > removes the second scrollbar.

**Comment by jp26jp** [comment]
This was resolved with the most recent update that was sent out today (01/03/2017). Feel free to reopen the issue if you are still experiencing a problem.
