### ISSUE TITLE
Add to bag enhancement : Price in the Button

### ISSUE THREAD

**Issue by HDRSky360** [j26design/Ecwid-Premium#49]
A great feature would be to have the ability to add the price in the "add to cart" button, like Ecwid does. 
![capture](https://cloud.githubusercontent.com/assets/24841434/21565016/f102f9a0-ce92-11e6-92f3-6f93f7cb66af.PNG)
It's nicer, and as you can see it on the screen shot, in some case, more readable than this :
![capture2](https://cloud.githubusercontent.com/assets/24841434/21565064/822e78be-ce93-11e6-9703-a6ddae7fd670.PNG)

**Comment by jp26jp** [comment]
This feature was just added to the widgets! If you're a lifetime member then it's been synced to your comp. Otherwise, you can just redownload the files that were sent out in the last update.
