### ISSUE TITLE
"Detach Log/Cart/Favorit V2.1.0" issue when couple with "Cart Counter V1.3.1"

### ISSUE THREAD

**Issue by HDRSky360** [j26design/Ecwid-Premium#50]
There is a bug when "Detach Cart" is couple with "Cart Counter". 
Indeed, in this case, the count of Items  located on the "Cart Counter" randomly desapear. 
For example, enlarge the height of a page (by adding ellements) can make the couter desapear.
Copy/paste them on a new virgin page, and it can both bug or re-work ...
This is very strange.

**Comment by jp26jp** [comment]
This issue should have been fixed in the last update that was sent out yesterday
