### ISSUE TITLE
referring to issue #44: Resizing the font of the ecwid navigation 2.0.1 widget. --> Widget was not updated

### ISSUE THREAD

**Issue by Squitsh** [j26design/Ecwid-Premium#51]
Hey John.

First, thank you so much for supporting your widgets with updates. I really appreciate that. Unfortunatly I had the resizing font problem with the navigation widget. Unfortunatly, this widget was not updated in your latest patch. It's still the version 2.0.1. from 15.07.16. 

Could you please update this navigation widget as well? Thank you very much in advance :-)

Cheers 
Markus

**Comment by jp26jp** [comment]
Dang, I wasn't able to reproduce the issue so I was hoping that something in the storefront changed to prevent the issue. Would you mind uploading a .muse file that [has this issue here](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN)

**Comment by Squitsh** [comment]
Sure. I sent you the muse file and a screenshot with the problem. I cant adjust the fontsize of this widget. You will find the widget on the "shop" page of the muse file.

**Comment by Squitsh** [comment]
And btw. another question. Its not refering to this specific widget. But how do I update a widget. Is there a posibility not to replace it on the canvas and to do all the settings again? This is a lot of work. So maybe just replacing the widget in the library and all muse sites with the older version now use the updated one? How would you do your update of widget on existing pages? I think many people will have this problem. Maybe you can do a video tutorial on youtube for boosting your channel. I did not find any tutorials about this. 

cheers :)

**Comment by jp26jp** [comment]
Okay the widget has been updated. If you're a lifetime member then it's been synced to your comp. Otherwise, you can just redownload the files that were sent out in the last update. And yes, you'll need to replace the existing widgets.
