### ISSUE TITLE
Specified catagories not showing

### ISSUE THREAD

**Issue by j-vic** [j26design/Ecwid-Premium#52]
Hi again, so I'm redesigning a site, and have integrated ecwid. I have 2 of the all storefront widgets on the one page, so maybe this is causing the issue. On the second widgets, I iputted a specific catagory like the first one, however nothing shows up when I preview the site in browser.

**Comment by jp26jp** [comment]
Watch this tutorial for help with setting up the [storefront](https://www.youtube.com/watch?v=7LPy9ODf8fQ)
