### ISSUE TITLE
Center align navigation

### ISSUE THREAD

**Issue by Bchila** [j26design/Ecwid-Premium#53]
under "menu placement" option, can you add a "center of container" option? thanks John!!!!!

**Comment by jp26jp** [comment]
The feature will be part of the next update!

**Comment by jp26jp** [comment]
This was added to the update that was sent out today!

**Comment by Bchila** [comment]
sweet! thank you!


ANNOUNCEMENT!!! WE NOW OFFER APPAREL & PRINTING SERVICES

Regards,
Brett Chila
Owner/Designer
Triune Design Studio
Jacksonville, Florida USA
Office: 1.904.300.3474

NEWSLETTER SIGNUP: http://eepurl.com/b3jGFL

www.TriuneDesignStudio.com          (website)
www.Behance.net/TriuneMultimedia    (online portfolio)
www.Facebook.com/TriuneDesignStudio (Facebook)
www.LinkedIn.com/in/BrettChila      (LinkedIn)
www.Google.com/+TriuneMultimedia    (Google+)

Graphic Design | Video/Motion Graphics | Websites & Hosting Solutions | Apparel & Printing

"Specializing in Graphic Design for the Apparel Industry"

"For God so loved the world, that He sent His one & only Son,
that whosoever would believe in Him, would not perish,
but have eternal life."  -John 3:16
