### ISSUE TITLE
Product types and sizes options not diaplaying

### ISSUE THREAD

**Issue by j-vic** [j26design/Ecwid-Premium#54]
Hi, the wores working fine, however, when clicking on a product, the types and size options I've put in for each product aren't showing at all.

I've looked through every option, maybe it's something I've missed?

**Comment by jp26jp** [comment]
Please upload your [.muse file here](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN)

**Comment by j-vic** [comment]
Just uploaded it

**Comment by jp26jp** [comment]
Okay so it looks like you're wanting your store to display as a catalog (meaning that you don't want them to be able to add anything to their cart) but you're wanting people to be able to see the options available?

**Comment by j-vic** [comment]
Yeah exactly! The prices not displaying was intentional as well. I just did that in the ecwid dashboard. So yeah, the clients wants the customers to see the product, and then call and ask or even come into the store.

**Comment by j-vic** [comment]
I still have a fair bit to go on the site, so sorry it's annoying to navigate through in preview.

**Comment by jp26jp** [comment]
Okay, I'll add more options to that section. For now, just add this to the `<head>` of the master page:

    <style>
    html#ecwid_html body#ecwid_body .ecwid div.ecwid-productBrowser-details-rightPanel div.ecwid-productBrowser-backgroundedPanelInner table {
        display: inherit!important;
    }
    </style>

> The prices not displaying was intentional as well. I just did that in the ecwid dashboard. 

I wasn't even aware you could do that in the dashboard. Is there a setting somewhere or did you do it with css?

**Comment by j-vic** [comment]
Um, I just did it with CSS. Thanks for the help. I'll try this out and let you know.

**Comment by j-vic** [comment]
Works perfect. Thanks so much man!

**Comment by jp26jp** [comment]
No problem!

**Comment by jp26jp** [comment]
This was added to the update that was sent out today!
