### ISSUE TITLE
Remove root breadcrumb link

### ISSUE THREAD

**Issue by Bchila** [j26design/Ecwid-Premium#55]
ive seen code for this in past.... need an option to not have the main storefront link appear in the breadcrumbs navigation. i can remove "category" text with widget, but not main storefront link. i want customer to NOT access the main storefront, only their area. thank you!

**Comment by jp26jp** [comment]
This feature was added to the next update!

**Comment by jp26jp** [comment]
This was added to the update that was sent out today!
