### ISSUE TITLE
2 store IDs in same site error

### ISSUE THREAD

**Issue by Bchila** [j26design/Ecwid-Premium#58]
John, i have store embedded to my site. I am hosting a pro shop of sorts for some friends (different store ID) and want to embed that store to same site (different page). i entered the store ID into widget, but instead of the new store showing up, it is displaying my other store that i already have on a different page of my site. But like i said, im using the new store ID in widget settings, weird! Can you help? thanks!

**Comment by Bchila** [comment]
UPDATE: even when i tried using the std HTML embed code by ecwid, i got same issue!

**Comment by Bchila** [comment]
UPDATE: i finally got it to work, but only by using the stand-alone website URL link ecwid provides via Iframe. We doesnt give me as much customization.

**Comment by jp26jp** [comment]
This happens if there is another widget on the page that requires the store ID. So check the shopping cart widgets, search widgets, etc.

**Comment by Bchila** [comment]
i deleted all of the widgets and placed fresh copies of widgets. only 
widget that needs store ID is the main storefront widget. i also tried 
this on a new blank page


ANNOUNCEMENT!!! WE NOW OFFER APPAREL & PRINTING SERVICES

Regards,
Brett Chila
Owner/Designer
Triune Design Studio
Jacksonville, Florida USA
Office: 1.904.300.3474

NEWSLETTER SIGNUP: http://eepurl.com/b3jGFL

www.TriuneDesignStudio.com          (website)
www.Behance.net/TriuneMultimedia    (online portfolio)
www.Facebook.com/TriuneDesignStudio (Facebook)
www.LinkedIn.com/in/BrettChila      (LinkedIn)
www.Google.com/+TriuneMultimedia    (Google+)

Graphic Design | Video/Motion Graphics | Websites & Hosting Solutions | Apparel & Printing

"Specializing in Graphic Design for the Apparel Industry"

"For God so loved the world, that He sent His one & only Son,
that whosoever would believe in Him, would not perish,
but have eternal life."  -John 3:16

**Comment by jp26jp** [comment]
Well that's not possible. Create a new Muse site and place the storefront widgets onto a page. Enter the store ID into the storefront widget and you'll see that you'll be able to change the widget to whatever store you'd like.
