### ISSUE TITLE
Allow spacing for buttons

### ISSUE THREAD

**Issue by orgongansol** [j26design/Ecwid-Premium#6]
<img width="860" alt="capture-21" src="https://cloud.githubusercontent.com/assets/19664141/15669141/0d5a3fd0-271f-11e6-96f7-5e24e462f138.png">

Hello there,

I would like to be able to set up the space between the separator and the title of the sections. Any way I can do it?

Thanks for your help.
Xavier

PS: love what you do :-)

**Comment by jp26jp** [comment]
I will add it as a feature to the next update!

**Comment by jp26jp** [comment]
This feature was added to Storefront Global V1.8.1. The update was just sent out via email!

**Comment by orgongansol** [comment]
That was quick. Thumb up.
