### ISSUE TITLE
Cart quanity does not display

### ISSUE THREAD

**Issue by TraylorHead** [j26design/Ecwid-Premium#60]
Store-front global 1.12.0

After messing around for a while I found that I had to turn on USE DEFAULT CART under Removables in Store Front Globals settings to get the quantity to display.  i do not see a default cart showing on my screen which I am grateful for.

**Comment by jp26jp** [comment]
So can I close the issue or is there something that's still not working?

**Comment by TraylorHead** [comment]
Yes I think so, I was think the default cart would be the floating cart, but it doesn't look like it is.
