### ISSUE TITLE
Ecwid Clean URL's on Business Catalyst

### ISSUE THREAD

**Issue by h2oonstone** [j26design/Ecwid-Premium#61]
John,
Any chance to configure Ecwid clean URL's on a Business Catalyst hosted site?
(No .htpaccess file)
Thanks, Ann

**Comment by jp26jp** [comment]
I will look into it and get back to you!

**Comment by h2oonstone** [comment]
Thanks John!

**Comment by jp26jp** [comment]
It doesn't seem to be possible but I'm trying to figure out if it is [here](https://forums.adobe.com/message/9323018#9323018).

**Comment by h2oonstone** [comment]
Great!
Can’t tell you what a relief it would be to be able to get my store items indexed.
I switched back to BC six months ago after switching to justhost  (which I found awful) to pick up the BC’s blogging module. I’d rather not switch again - but will consider if I can get my 250+ items indexed!
Fingers crossed, Ann

**Comment by jp26jp** [comment]
[It seems that this isn't possible with business catalyst](https://forums.adobe.com/message/9323018#9323018)!

**Comment by h2oonstone** [comment]
Thanks for checking that out John.

I also  asked BC support - this is what they said…
I can understand your issue, However, the issue is because of how Ecwid works.
In BC, we won't be able to change the Url of the pages or the product catalogues as the Url won't link to the correct product.

You can refer to this Url as it may help : https://www.ecwid.com/forums/showthread.php?t=16317 <https://www.ecwid.com/forums/showthread.php?t=16317>
I'm afraid, BC won't be able to make any changes in the Ecwid generated Url to make it SEO friendly.


I am trying to get the clean url widget to work for me on a Dotster hosted site - have posted my issue here

https://github.com/j26design/Ecwid-Premium/issues/63
