### ISSUE TITLE
My store is crashing

### ISSUE THREAD

**Issue by bossgus** [j26design/Ecwid-Premium#62]
for some reason my store is crashing 
http://bassari.com.mx/tienda-en-linea.html
any Ideas ?

thanks

**Comment by jp26jp** [comment]
[Can you upload your muse file here](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN).

**Comment by bossgus** [comment]
For some reason, now it's working !! Thank you !!!

Enviado desde mi iPhone
