### ISSUE TITLE
Bug - Ecwid Clean URL's

### ISSUE THREAD

**Issue by h2oonstone** [j26design/Ecwid-Premium#63]
Hi John -

Since I couldn't use the clean URL widget with my site on Business Catalyst - I went ahead and bought h2oonstone.store and hosted it on Dotster to put my Ecwid store on. (Thanks for checking that out.)

I'm having a problem getting it to work though - as soon as I check Enable Clean URLs and try to FTP upload from Muse - Muse crashes...

![screen shot 2017-02-15 at 7 48 51 pm](https://cloud.githubusercontent.com/assets/19439377/23002307/097b1fcc-f3b8-11e6-9b01-e0f76efc0961.png)

I tried uploading it w/ filezilla - it looked as if it worked but then gave me the 404 error on reload (I used incognito like your example)

I've reset the muse file and removed the RewriteEngine code on the live page - http://h2oonstone.store/index.html

this is the code I used for on the .htaccess 

![screen shot 2017-02-15 at 7 29 22 pm](https://cloud.githubusercontent.com/assets/19439377/23002497/13b1a5c8-f3b9-11e6-9134-987fc5cc765c.png)

Let me know if you want me to send the muse file

**Comment by h2oonstone** [comment]
I just uploaded the muse file to dropbox - thanks, Ann

**Comment by jp26jp** [comment]
I'll need access to your server to be able to take a look. If you don't mind giving me temporary access, please send the credentials to [john@j-26.com](mailto:john@j-26.com)

**Comment by h2oonstone** [comment]
Thanks - I sent them.

**Comment by h2oonstone** [comment]
John have you seen the new post from Ecwid 2/15/17 about the clean urls - https://www.ecwid.com/forums/showthread.php?t=39019

Looks like the developer information is here - https://developers.ecwid.com/api-documentation#seo-friendly-urls

**Comment by jp26jp** [comment]
Yes, I've been working with them before that post. I haven't had a chance to look at your site yet.

**Comment by h2oonstone** [comment]
John - I tried again with a new file and got Muse to stop crashing - it loads as if it works - but on reload it returns a 404 - I'll send the new file to dropbox - credentials are the same

**Comment by jp26jp** [comment]
Okay sounds good!

**Comment by h2oonstone** [comment]
Hey John -
I was messing with it again today and just to see what would happen I copied the sample rewrite code in your tutorial (not my generated one) into my .htaccess file and the Clean URLs worked.

**Comment by jp26jp** [comment]
That code only works if your store is located in a `/store/` subfolder. For example, [this URL](http://www.h2oonstone.store/checkout/shipping) doesn't really work. I've updated the generator code to work with stores located on the homepage. Regenerate the code for your store and it should work.

**Comment by jp26jp** [comment]
If the generated code doesn't look any different, you may need to reload the generator page.

**Comment by h2oonstone** [comment]
And, I should use http://www.h2oonstone.store/index.html (not http://www.h2oonstone.store) to generate the code?

**Comment by jp26jp** [comment]
Correct

**Comment by h2oonstone** [comment]
I just generated the code - and updated it

this is what I got when I was testing it

**Comment by jp26jp** [comment]
Not seeing anything?

**Comment by h2oonstone** [comment]
This is the screen shot
![screen shot 2017-02-25 at 3 49 14 pm](https://cloud.githubusercontent.com/assets/19439377/23334721/f21ea228-fb72-11e6-9fd3-d031e8b9f2a3.png)

**Comment by h2oonstone** [comment]
I posted a screen shot on github 

(it didn’t pick it up from email)

**Comment by jp26jp** [comment]
I found the issue, updated the code, and now it's working!
