### ISSUE TITLE
Cart Counter 

### ISSUE THREAD

**Issue by EP1975** [j26design/Ecwid-Premium#67]
I'm using the cart counter right at the top of my pages so it can be accessed from anywhere within the site. However, when clicking on the cart, the cart window opens behind the top navigation and is stuck at the top of the page. Only half is visible and can't be scrolled either.

**Comment by jp26jp** [comment]
What's your URL?

**Comment by EP1975** [comment]
Think I already solved it by adding a bit of html on the shop page.
The website is fibrax.org <http://fibrax.org/> in case you’re interested.

Thanks for coming back to me though.
_ _

Ellen Parzer
