### ISSUE TITLE
Detached Login Favorites and Cart

### ISSUE THREAD

**Issue by susan032301** [j26design/Ecwid-Premium#68]
Hey,

I'm having issues with the detached login, favorites and cart. I put the widget on the muse page, link up the store URL and preview it in the web browser...but it is 100% dead. It does not link to anything. It acts as  link-less text on the page and nothing else. I've tried several different things and I'm at the point of pulling my hair out. I'm using a Windows computer with the latest version of Muse.

I appreciate your help!

**Comment by jp26jp** [comment]
Okay, I'll look into what's going on.

**Comment by jp26jp** [comment]
I just tried it and it's not causing any issues. Can you send your [.muse file here](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN)

**Comment by susan032301** [comment]
I'll send a mock muse file with all the problems stated either late today or tomorrow. Thanks for looking into this.

**Comment by jp26jp** [comment]
An update was sent out yesterday that fixes this issue!
