### ISSUE TITLE
J-26 Ecwid Premium Widget for Adobe Muse

### ISSUE THREAD

**Issue by sk8phil** [j26design/Ecwid-Premium#7]
1. Add hover state to the Shopping Cart widget.
2. Remove SKU clashes with the “Back to Store” button.
3. The search bar appears much larger than intended when I preview it in browser.

**Comment by jp26jp** [comment]
Which version of the widget are you using? Would you mind uploading your [Muse file here](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN)

**Comment by sk8phil** [comment]
Version V1.2.0.

**Comment by jp26jp** [comment]
Taking a look!

**Comment by sk8phil** [comment]
For Item #3, I forgot to add that this oversize issue occurs when I mess with the border options; e.g., when I only add the bottom border.

**Comment by jp26jp** [comment]
Okay, 1 and 2 were added/fixed in the update that was just sent out. I'm going to close this issue and I've opened one specifically for the search bar issue so I know to come back to that. [That issue will be located here](https://github.com/j26design/Ecwid-Premium/issues/8).

**Comment by sk8phil** [comment]
Thanks for that.  What do I do to obtain the update?  Do I need to download the latest version?  Also, with regards to my questions 4 & 5, do you have apps that can do this?  Thanks.

**Comment by sk8phil** [comment]
Thanks for that.  What do I do to obtain the update?  Do I need to download
the latest version?

Also, with regards to my questions 4 & 5, do you have apps that can do
this?  Thanks.

-Phil

On Sat, Jun 4, 2016 at 3:45 AM, John R Perry <notifications@github.com>
wrote:

> Okay, 1 and 2 were added/fixed in the update that was just sent out. I'm
> going to close this issue and I've opened one specifically for the search
> bar issue so I know to come back to that. That issue will be located here
> <https://github.com/j26design/Ecwid-Premium/issues/8>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/j26design/Ecwid-Premium/issues/7#issuecomment-223749175>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS019-68c6VgnNoYY3JXUXkvFm9HmPbAks5qIVdYgaJpZM4IuBGt>
> .
>



-- 
-Phillip Romero

**Comment by jp26jp** [comment]
The update is sent out vie email. Check your spam folder and if you didn't receive it, let me know and I'll see what happened. And no, I don't have widgets for the other two.

**Comment by sk8phil** [comment]
Thanks for the reply. I didn't receive the update, and I checked my spam mail. Can you please resend it? Thanks. 

Phillip Romero

Sent from my iPhone

On Jun 6, 2016, at 3:25 PM, John R Perry <notifications@github.com> wrote:

The update is sent out vie email. Check your spam folder and if you didn't receive it, let me know and I'll see what happened. And no, I don't have widgets for the other two.

**Comment by jp26jp** [comment]
Yes, what email did you use?

**Comment by sk8phil** [comment]
Please use romero.phil@gmail.com 
Thanks. 

Phillip Romero

Sent from my iPhone

On Jun 7, 2016, at 2:57 AM, John R Perry <notifications@github.com> wrote:

Yes, what email did you use?

**Comment by jp26jp** [comment]
That email isn't pulling anything up. Did you happen to have another email
you might have purchased it with?

**Comment by sk8phil** [comment]
Oh. The purchase was done with my wife's email:

Jennifer@bloomieshandmade.com 

Can you send it again?  Thanks. 

Phillip Romero

Sent from my iPhone

On Jun 7, 2016, at 2:42 PM, John R Perry <notifications@github.com> wrote:

That email isn't pulling anything up. Did you happen to have another email
you might have purchased it with?

**Comment by jp26jp** [comment]
Okay, it was just sent!

**Comment by sk8phil** [comment]
Thanks.  I just downloaded it.  Do delete out the old one and install this
one?

On Tue, Jun 7, 2016 at 10:48 PM, John R Perry <notifications@github.com>
wrote:

> Okay, it was just sent!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/j26design/Ecwid-Premium/issues/7#issuecomment-224494508>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS0194VVrZVFHtjFRH6r_W4601iOaSF2ks5qJleWgaJpZM4IuBGt>
> .
>



-- 
-Phillip Romero

**Comment by sk8phil** [comment]
Unfortunately, it is not working right.  I change the state color to white
and the rollover to a dark blue, and it do not want to keep those colors.
Instead, when I preview it, it pushes the normal state to be baby blue and
the rollover state to be red.  Also, when you first drop it into Adobe
Muse, it wouldn't allow me to pick move it to the top layer.  I had to trip
it out by associating it to another layer and then changing it to the
desire layer.  This then allowed me to move it to top.  Can you please
help.  Perhaps would be easier to talk over the phone.  Thanks.

-Phil
cell: 209-603-8077

On Mon, Jun 13, 2016 at 8:58 PM, Phillip Romero <romero.phil@gmail.com>
wrote:

> Thanks.  I just downloaded it.  Do delete out the old one and install this
> one?
>
> On Tue, Jun 7, 2016 at 10:48 PM, John R Perry <notifications@github.com>
> wrote:
>
>> Okay, it was just sent!
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/j26design/Ecwid-Premium/issues/7#issuecomment-224494508>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AS0194VVrZVFHtjFRH6r_W4601iOaSF2ks5qJleWgaJpZM4IuBGt>
>> .
>>
>
>
>
> --
> -Phillip Romero
>



-- 
-Phillip Romero

**Comment by sk8phil** [comment]
Please disregard the color issue part.  I just realized that I am to edit
the colors in the styling, not text panel.  I ill continue exploring it.
Thanks.

On Mon, Jun 13, 2016 at 9:20 PM, Phillip Romero <romero.phil@gmail.com>
wrote:

> Unfortunately, it is not working right.  I change the state color to white
> and the rollover to a dark blue, and it do not want to keep those colors.
> Instead, when I preview it, it pushes the normal state to be baby blue and
> the rollover state to be red.  Also, when you first drop it into Adobe
> Muse, it wouldn't allow me to pick move it to the top layer.  I had to trip
> it out by associating it to another layer and then changing it to the
> desire layer.  This then allowed me to move it to top.  Can you please
> help.  Perhaps would be easier to talk over the phone.  Thanks.
>
> -Phil
> cell: 209-603-8077
>
> On Mon, Jun 13, 2016 at 8:58 PM, Phillip Romero <romero.phil@gmail.com>
> wrote:
>
>> Thanks.  I just downloaded it.  Do delete out the old one and install
>> this one?
>>
>> On Tue, Jun 7, 2016 at 10:48 PM, John R Perry <notifications@github.com>
>> wrote:
>>
>>> Okay, it was just sent!
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/j26design/Ecwid-Premium/issues/7#issuecomment-224494508>,
>>> or mute the thread
>>> <https://github.com/notifications/unsubscribe/AS0194VVrZVFHtjFRH6r_W4601iOaSF2ks5qJleWgaJpZM4IuBGt>
>>> .
>>>
>>
>>
>>
>> --
>> -Phillip Romero
>>
>
>
>
> --
> -Phillip Romero
>



-- 
-Phillip Romero

**Comment by jp26jp** [comment]
Yes, delete the old one. Okay, let me know if anything else comes up

**Comment by sk8phil** [comment]
Alright, I finished testing the shopping cart.  I am having a few issues:
1.) Even though I have it centered on the menu bar I created, when I
preview it, it places it off-centered
2.) Even though I have the correct store ID and URL imputed, when I click
on the shopping cart while in preview, it sends me to a page entitled,
"Page not fond"
3.) I have placed the shopping cart in my master page so it is on every
page.  When I preview the master page and rollover, the mouse pointer
becomes a hand.  However, when I rollover it while previewing the store
page, the count does not appear and the mouse pointer does not become a
hand.

Please advise.  Thanks.

On Mon, Jun 13, 2016 at 9:27 PM, Phillip Romero <romero.phil@gmail.com>
wrote:

> Please disregard the color issue part.  I just realized that I am to edit
> the colors in the styling, not text panel.  I ill continue exploring it.
> Thanks.
>
> On Mon, Jun 13, 2016 at 9:20 PM, Phillip Romero <romero.phil@gmail.com>
> wrote:
>
>> Unfortunately, it is not working right.  I change the state color to
>> white and the rollover to a dark blue, and it do not want to keep those
>> colors.  Instead, when I preview it, it pushes the normal state to be baby
>> blue and the rollover state to be red.  Also, when you first drop it into
>> Adobe Muse, it wouldn't allow me to pick move it to the top layer.  I had
>> to trip it out by associating it to another layer and then changing it to
>> the desire layer.  This then allowed me to move it to top.  Can you please
>> help.  Perhaps would be easier to talk over the phone.  Thanks.
>>
>> -Phil
>> cell: 209-603-8077
>>
>> On Mon, Jun 13, 2016 at 8:58 PM, Phillip Romero <romero.phil@gmail.com>
>> wrote:
>>
>>> Thanks.  I just downloaded it.  Do delete out the old one and install
>>> this one?
>>>
>>> On Tue, Jun 7, 2016 at 10:48 PM, John R Perry <notifications@github.com>
>>> wrote:
>>>
>>>> Okay, it was just sent!
>>>>
>>>> —
>>>> You are receiving this because you authored the thread.
>>>> Reply to this email directly, view it on GitHub
>>>> <https://github.com/j26design/Ecwid-Premium/issues/7#issuecomment-224494508>,
>>>> or mute the thread
>>>> <https://github.com/notifications/unsubscribe/AS0194VVrZVFHtjFRH6r_W4601iOaSF2ks5qJleWgaJpZM4IuBGt>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> -Phillip Romero
>>>
>>
>>
>>
>> --
>> -Phillip Romero
>>
>
>
>
> --
> -Phillip Romero
>



-- 
-Phillip Romero

**Comment by sk8phil** [comment]
Also, the SKU still clashes with the 'Back to Store' button.

**Comment by jp26jp** [comment]
Okay, upload the Muse file again.

**Comment by jp26jp** [comment]
I've created a new issue with the new errors. [Follow updates over here](https://github.com/j26design/Ecwid-Premium/issues/10)

**Comment by sk8phil** [comment]
I have uploaded it in the same like you have emailed to me in the past.
Thanks.

-Phil

On Mon, Jun 13, 2016 at 11:17 PM, John R Perry <notifications@github.com>
wrote:

> Okay, upload the Muse file again.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/j26design/Ecwid-Premium/issues/7#issuecomment-225789504>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS0190eg186ejiTr60rZpL-bHo84T-ILks5qLkdfgaJpZM4IuBGt>
> .
>



-- 
-Phillip Romero

**Comment by jp26jp** [comment]
None of the widgets have been updated. Update the widgets and let me know if you're having the same problems.

**Comment by sk8phil** [comment]
What file did I send to you?  Was it Bloomies Website 2016.06.13x?

I did delete the old shopping cart and storefront and replace them with the
latest version that I had to download.  Please look at the version and you
will see Shopping Cart V1.3.0 and Storefront V8.16.0 (see attached).  Those
version are newer than the previous ones.  Am I incorrect on those
versions?  Thanks.

On Tue, Jun 14, 2016 at 7:04 AM, John R Perry <notifications@github.com>
wrote:

> None of the widgets have been updated. Update the widgets and let me know
> if you're having the same problems.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/j26design/Ecwid-Premium/issues/7#issuecomment-225891126>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS0190b_38lDVb1mk9PR4HfXGlczTEVKks5qLrT9gaJpZM4IuBGt>
> .
>



-- 
-Phillip Romero

**Comment by jp26jp** [comment]
The storefront was sent out in the last email is V8.17.2

**Comment by sk8phil** [comment]
I realized what had happened.  You had sent out two emails, and I had only looked at the first one.  I guess some updates were done after that first email.  I'll try tinkering with this version and get back to you.  Thanks.

**Comment by sk8phil** [comment]
Out of curiosity, this latest update is for the storefront; I do not see a newer shopping cart widget.  How does this update fix the issues I'm having with the shopping cart if that is another widget?  Thanks.

**Comment by jp26jp** [comment]
You mentioned the issue with the shopping cart after the email was sent out
so no it wouldn't have an update for something I didn't know about.

Once you update everything let me know if you're having the shopping cart
issue. If you are, then I can take a look. But I need to know if the new
widgets are causing the problem.

**Comment by sk8phil** [comment]
10-4. I'll look into when I get some time. Thanks. 

Phillip Romero

Sent from my iPhone

On Jun 15, 2016, at 4:30 PM, John R Perry <notifications@github.com> wrote:

You mentioned the issue with the shopping cart after the email was sent out
so no it wouldn't have an update for something I didn't know about.

Once you update everything let me know if you're having the shopping cart
issue. If you are, then I can take a look. But I need to know if the new
widgets are causing the problem.

**Comment by sk8phil** [comment]
I just installed the latest version (V8.17.3), and almost everything looks good.  There is still one issue that is prevalent.  The counter appears on every page except for the “Shop page”.  Can you please advise as to what is going on here?  Also, is there a way that I can easily transfer all of my options and colors that I have marked in the older version on to the newer version?  Thanks.

**Comment by jp26jp** [comment]
No there isn't a way to transfer any previously selected options.

For the counter, please open a new issue and upload your updated muse file.

**Comment by sk8phil** [comment]
Done. Thanks.

On Wed, Jun 22, 2016 at 7:40 PM, John R Perry <notifications@github.com>
wrote:

> No there isn't a way to transfer any previously selected options.
>
> For the counter, please open a new issue and upload your updated muse file.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/j26design/Ecwid-Premium/issues/7#issuecomment-227934751>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS019z37hLH20eWWu0kTfHvMkYXGc9JHks5qOfIIgaJpZM4IuBGt>
> .
>



-- 
-Phillip Romero
