### ISSUE TITLE
Storefront Main v9.0.3 always directs to test surf company

### ISSUE THREAD

**Issue by illumedi** [j26design/Ecwid-Premium#71]
Have replaced ecwid store ID but it only lands on test company site (ecwid's example surf company).  Was fine with v9.0.1.  

Not sure if related but also keeps showing "Unable to generate thumbnail" on Muse store page.  Have tried multiple times deleting just Main and adding just Main but only ever shows checkerboard with the warning.  
 Other widgets are showing fine.

**Comment by jp26jp** [comment]
It's not related to the thumbnail and it's not related to an update. If you are using a shopping cart or another widget that requires the store ID, make sure that it is using your store ID. The only possible way that the default store can be displayed is if you are using a widget that is pointing to the default store ID.

**Comment by illumedi** [comment]
Everything works on v9.0.1; I remove v9.0.1 widgets; I insert v9.0.3 set and change the store ID in Main to mine and yet it points to that default store ID (surf store).  I've checked each of your new widgets and cannot find any other visible field with store ID.  Since your widgets are the only ones that I have changed, how can it be another widget?

**Comment by jp26jp** [comment]
Feel free to send your store to john@j-26.com but I'm positive that the
only way the widget can generate the default store is if the default store
ID is left in the widget.
