### ISSUE TITLE
Global V1.14.0 - Product Grid V1.12.2

### ISSUE THREAD

**Issue by allin1media** [j26design/Ecwid-Premium#73]
Hey John,

Can we re-introduce the options for;

Global-
remove sku
remove quantity

Product Grid-
remove product price

I'm converting store to use Product Layout Splitter - Just updated all storefront widgets and I'm missing these features. I know things have to get moved sometimes. Am I overlooking these somewhere else?

BTW - thanks for color picker update!!

**Comment by jp26jp** [comment]
They're in Settings > Design
