### ISSUE TITLE
Scrolling Issue

### ISSUE THREAD

**Issue by illumedi** [j26design/Ecwid-Premium#74]
My Master page has a header and all site pages except the storefront scroll under the page header.  storefront scrolls over the header.  I have moved the storefront box to the back, slid Top of Store down further but nothing seems to change.  Is there a setting I can't seem to find for this? (v9.0.3 storefront)

**Comment by jp26jp** [comment]
[Upload your Muse file here and I'll take a look](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN).

**Comment by illumedi** [comment]
Thanks.

**Comment by illumedi** [comment]
sorry hit the wrong button

**Comment by jp26jp** [comment]
You've put the store in the same layer as the navigation. Put the store into the page layer and it will work as expected.
