### ISSUE TITLE
Grid Thumbnail sizes

### ISSUE THREAD

**Issue by j-vic** [j26design/Ecwid-Premium#75]
Hey man,

Just wondering if there is a way to change the thumbnail sizes on grid view. At the moment, they're all different sizes. I tried the thumbnail size settings in Ecwid itself, but the widget seems to be ignoring those settings.

**Comment by jp26jp** [comment]
The images can be adjusted in the Ecwid dashboard under *Settings > Design*. Just scroll to the bottom and you'll see the options.

**Comment by j-vic** [comment]
Yeah I tried that and set the size to 230px. It won't work for some reason.

http://geishaceramics.com.au/categories.html#!/Wall-Tiles/c/23632445/offset=0&sort=nameAsc
