### ISSUE TITLE
Product detail splitter bug

### ISSUE THREAD

**Issue by mtm1992** [j26design/Ecwid-Premium#76]
Hello I really like this widget but theres a bug! when I export it, the buying and description section moves down, but only sometimes!

it moves more down when I seth the product detail width to 40%

<img width="1089" alt="skaermbillede 2017-06-13 kl 16 21 46" src="https://user-images.githubusercontent.com/29405114/27087190-9672058c-5054-11e7-80ea-585232222187.png">

Hope you can fix it!

Mads from Denmark

**Comment by jp26jp** [comment]
Can you upload your [Muse file here](https://www.dropbox.com/request/jTLS8SM5TU547RCjpgRN)
