### ISSUE TITLE
Preview & view in browser loading "demo" store 

### ISSUE THREAD

**Issue by Pogonotrophics** [j26design/Ecwid-Premium#77]
After being correct and loading my actual store, when going to PREVIEW within Muse or viewing in browser the storefront and navigation started to load the default demo store that is pre-setup [ID 1003]in the widgets. I updated to the newest version of the widgets the next day and I am still having this issue. This current site has not been uploaded as it is a complete re-working of my site. My current active site is operating correctly.
I also noticed that I cannot change the navigation bar's background color completely now - the buttons don't change, but the rest will.
As part of this work I reverted the base unedited Ecwid theme as I was having text consistency issues. It was after then that I believe this issue started.
Also of note, tonight when viewing in browser I received the "items have changed from server..." notice from my browser.

**Comment by jp26jp** [comment]
This issue doesn't make any sense. Please summarize and clarify the issue.

**Comment by Pogonotrophics** [comment]
John,

 

I don’t know what else to summarize. 

 

When viewing the site I am working on within Muse’s preview and preview in browser I do not see my store but your demo store. It worked properly for some time and then after making a few more changes (for the scalable screen sizes) it started doing it. At first through Muse’s preview and thinking there was some glitch I opened it in the browser to view and found the same thing. I immediately went back to verify all settings and found that nothing had changed; that in fact my Ecwid ID remained. I closed the site and program. Re-opened later, once I saw that the widgets had just updated, and using the new widgets encountered the same issue.

 

I am not sure if there is a cache within Muse that may be retaining a setting or finding the demo ID and making it priority… It is very weird and I cannot seem to find any reason why this would happen – as it never happened before and I saw no previous instances reported by others. But, I cannot trust continuing to build this site and to publish it to have this happen to my customers.

 

I can package up this file to send to you if you would like to view it….

 

Thank you

 

John C Dodge

CEO

J&L Pogonotrophics

www.pogonotrophics.com

**Comment by jp26jp** [comment]
So in summary, the wrong store is appearing?

This can only happen if you are using another widget that has the wrong Ecwid ID.

**Comment by Pogonotrophics** [comment]
Well, one might think that.

I have validated every instance where I enter my Ecwid ID or website and it is correct. Yet this keeps happening.

In editing it appears my store is loaded, but once I go to Preview or View in Browser that is not the case.

 

I just made a video of this to help – I am not being very polite in it as I am not happy.

 

Thank you

John

**Comment by Pogonotrophics** [comment]
Greetings,

 

I just rebooted again and it seems all better.

 

I have to say that in the middle of all this Adobe CC had some upgrades and I am encountering all sorts of weird behaviors out of the applications I use. Illustrator alone is made my life hell for the last 48 hours.

 

I honestly have no idea what caused this or why it was happening… only thing I can think of is Muse did not want to play nice for a while.

 

Thank you

John
