### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by riccng** [j26design/Ecwid-Premium#79]
Good morning,
I am having issues with the icons of the Ecwid Premium Widget.

My customer just noticed they have disappeared from all the Ecwid buttons (cart, add to cart, checkout and so on). I tried to link the icon stylesheet in the head of the page as suggested at this link: 
https://www.j-26.com/resources/icon-stylesheet/
but the problem persists. 
Please let me know how to procede to solv this issue as soon as possible. My client needs the website to be fully operative immediately. 

Isn’t it possible to download these icons and host them elsewhere? (I would like to upload em to my customer’s hosting server, I need to avoid having this issue in the future).

Thanks in advance for your reply
Have a nice day

Riccardo Negri

**Comment by jp26jp** [comment]
What's the URL?

**Comment by riccng** [comment]
Www.review-official.com (I sent it to you privately by mail)
I managed to disable (from the widget options) almost all the icons which
were not loading correctly, but I would like them to be there..
Now all the buttons of the shop have no icons. I managed to replace the
cart counter icon with a custom svg, removing the widget original icon.
I still cannot manage to replace the "x" icon used as a bottom to remove
products from the cart.   I am attaching a screen shot of a previous
version of the site.

Thanks for your help.

Riccardo


Il 25 ago 2017 01:31, "John R Perry" <notifications@github.com> ha scritto:

**Comment by jp26jp** [comment]
Can you publish the site to a temporary URL so I can see what's going on?

**Comment by riccng** [comment]
Hello John,
I published it on www.review-official.com/temp
I am attaching a screenshot of the problem just to be more clear.
Thanks for your help.
![icons](https://user-images.githubusercontent.com/31275308/29779679-91e3a3c2-8c13-11e7-8772-87bf5141136a.JPG)

**Comment by riccng** [comment]
Hello John,
is there some news about the mentioned issue?
Thanks in advance for your attention towards my request.

Have a nice day.

**Comment by jp26jp** [comment]
I checked multiple devices and multiple browsers and the icons are appearing.

<img width="295" alt="screenshot 2017-09-04 05 42 18" src="https://user-images.githubusercontent.com/18344950/30025036-ebf88768-9133-11e7-8a99-3febdc5e3735.png">
