### ISSUE TITLE
The search bar appears much larger than intended when I preview it in browser

### ISSUE THREAD

**Issue by jp26jp** [j26design/Ecwid-Premium#8]

**Comment by sk8phil** [comment]
Any update on this?  Thanks.

**Comment by jp26jp** [comment]
Not yet. I should be able to take a look in the next 48 hours.

**Comment by sk8phil** [comment]
Was this updated?  I did not see this in the Ecwid Premium package.  Thanks.

**Comment by jp26jp** [comment]
not yet

**Comment by jp26jp** [comment]
I'm not able to replicate this problem. Can you send me a muse file where this is happening?

**Comment by jp26jp** [comment]
If you redownlaod the widgets that were sent out with the Storefront Update (not the shopping cart one) it will include a new version of the search bar which hopefully won't give you any issues.

**Comment by sk8phil** [comment]
I'll try it out and get back to you.

On Thu, Jun 23, 2016 at 4:33 AM, John R Perry <notifications@github.com>
wrote:

> If you redownlaod the widgets that were sent out with the Storefront
> Update (not the shopping cart one) it will include a new version of the
> search bar which hopefully won't give you any issues.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/j26design/Ecwid-Premium/issues/8#issuecomment-228022749>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS0195RMftLhxanydEQ-tKQMaXseCx3eks5qOm7_gaJpZM4IuGrd>
> .
>



-- 
-Phillip Romero

**Comment by sk8phil** [comment]
Yes.  I'll upload it in a second.  Note, the latest version that I have is
V2.0.0​.  I placed an experimental search box (below the header) and you
can see it becomes much larger when you resize it and then look at it while
in Preview mode.

**Comment by jp26jp** [comment]
V3.0.0 is the one that was sent out.

**Comment by sk8phil** [comment]
I'll check it out this week and get back to you.  Thanks.

**Comment by sk8phil** [comment]
I did a couple quick tests with the Search bar V3.0.0 and it appears to be working correctly.  Thanks.

**Comment by jp26jp** [comment]
Awesome. Thanks for the update!
