### ISSUE TITLE
Impossible to update my theme via Envato Market Plugin

### ISSUE THREAD

**Issue by Cadasse** [j26design/Ecwid-Premium#81]
Hi, 
I've installed the Envato Market Plugin to update my wordpress theme. I can see there is an update available through the plugin but as I clic on "Update available" nothing happen. 
Do you guys have any ideas on how I have to proceed ? 
David
![salientcapture](https://user-images.githubusercontent.com/32837163/31607469-b770477e-b26c-11e7-849d-bfe2b3ce233a.JPG)

**Comment by jp26jp** [comment]
This doesn't seem to have anything to do with the Ecwid (Premium) widget for Muse.
