### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by wfellinger** [j26design/Ecwid-Premium#82]
Hello, 
I use the J-26 Ecwid widget and I like it a lot. When I'm working on the mobile version of the webstore the minimum weight of the storefront is 536 px. I want it to be 358. What am I doing wrong?
![ecwid store](https://user-images.githubusercontent.com/33391489/32414068-39ce0104-c21f-11e7-99ae-7e3fc8de6c62.jpg)

**Comment by jp26jp** [comment]
Can you email me a version of the Muse file that only contains the store page?

**Comment by wfellinger** [comment]
Hello John R Perry,

I been busy with the mobile version and I solved the problem I sent you. I do have another problem. The Ecwid store is not completely in the centre (see mobile.png). I don’t know what I have to change. As you can see in store.png the store is centered.

Regards, Wim Fellinger

**Comment by jp26jp** [comment]
There's no image.
