### ISSUE TITLE
product splitter widget for ecwid

### ISSUE THREAD

**Issue by lubanda** [j26design/Ecwid-Premium#83]
hello i have purchased you ecwid widget pack and the product splitter widget is doing something rather odd. it is pushing down the panel to the bottom of the page. is there a fix to this or am i doing something wrong?

www.igloled.net is the website

**Comment by jp26jp** [comment]
Can you send a copy of the Muse file that only contains the page with the
store to john@j-26.com?

**Comment by lubanda** [comment]
yes i will send it right now!

**Comment by jp26jp** [comment]
The store you sent is only using the Product Details Layout Splitter which cannot be done. You need to use a minimum of Main, Global, Product Grid, and Buttons. I'm closing this issue but feel free to reopen it once you have swapped the existing store with the J-26 Ecwid widgets.
