### ISSUE TITLE
404 error whe i relod any page from my store

### ISSUE THREAD

**Issue by lexucd** [j26design/Ecwid-Premium#85]
Please help me with this 404 error since i ran out of powers trying to fix it. I've built this store with Muse ecwid and bought you store widget. My website is gerovital.store
and the store is at https://gerovital.store/store.html. Try clicking on any category and the reloading the page... I did all the steps from your tutorial and video but still no luck. Please help me with this problem because i am sure that i am missing some small detail or checkbox :) 
Thank you in advance for the time you took for my problem!

Best regards, 
 Cristian

**Comment by jp26jp** [comment]
When I open a category and reload the page, it works fine. Are you still
having an issue?

**Comment by lexucd** [comment]
Hi,
 That is because i had to uncheck the clean URLs and delete te rules from
.htacces file. i Went back to basics :(
