### ISSUE TITLE
Store Front default configuration Error

### ISSUE THREAD

**Issue by Asiyah1122** [j26design/Ecwid-Premium#89]
It says unable to generate thumbnail

**Comment by jp26jp** [comment]
That doesn't mean the store doesn't work. Does it load when you export the page to a browser?

**Comment by Asiyah1122** [comment]
Peace king, I didn't export it I selected preview from the muse app but
nothing loaded in the preview

**Comment by jp26jp** [comment]
Preview it in the browser
