### ISSUE TITLE
Shipping Cell - Make cell height bigger

### ISSUE THREAD

**Issue by orgongansol** [j26design/Ecwid-Premium#9]
<img width="961" alt="capture-25" src="https://cloud.githubusercontent.com/assets/19664141/15892465/14eafb3e-2d7a-11e6-8177-c96cef17ef97.png">

In order to use any font, the cell height must be changeable. Right now, it is causing a padding where users can't see their country.

**Comment by jp26jp** [comment]
This feature is almost added and will be part of the next update!

**Comment by jp26jp** [comment]
This feature was added to _Global V1.9.0_ and the update was just sent out!
