### ISSUE TITLE
Unable to use Ecwid plug in with Muse

### ISSUE THREAD

**Issue by CharlesH831** [j26design/Ecwid-Premium#90]
On 1/15/18 at the advice of an associated with Ecwid I paid $20 for your premium plug in to allow me to integrate my on line store with Adobe Muse. So far I've been unable to use your software. I've followed the instructions shown to me in your video and and when I try to drag the widget into the the web page, all I get is a big checkered box with the messages "Unable to generate thumbnail" or something similar. I spoke to a Ecwid rep via on-line chat about this and she told me to download the plug in and directed me to the same page and instructions I originally went to when I downloaded the files. Could someone please contact me and let me know what the heck I'm doing wrong. I tried to contact you via e-mail at john@j-26.com and the e-mail was sent back as undeliverable. Could someone please contact me at charles@harrisbandinstruments.com and tell me what the heck I'm doing wrong. 
Thank you
Charles Harris 
Harris Band Instruments
Covington, GA 
770-787-2095

**Comment by CharlesH831** [comment]
![muse with j-26](https://user-images.githubusercontent.com/35538474/35058788-fce00f84-fb86-11e7-91c9-e33ac9c7ccfc.JPG)

This is what I see when I attempt to use your plug in. 

Thanks 
Charles Harris

**Comment by jp26jp** [comment]
If the thumbnail doesn't generate, it doesn't mean the widget doesn't work
