### ISSUE TITLE
Storefront not showing my products

### ISSUE THREAD

**Issue by maximumstreetwear** [j26design/Ecwid-Premium#92]
Ive entered my store id. deleted the widget and redownloaded it and removed it from muse and put it back in. no matter what I do once I export it does not show my stores products.

**Comment by jp26jp** [comment]
It's likely because you have a widget that has the wrong store ID. It's impossible for the widget to show any other products than your own when the correct store ID to be entered.

**Comment by maximumstreetwear** [comment]
this is what I see although none of these are on my store and ive copy and
pasted the ID directly from my store
